In [ ]:
# WHEN THE POPULATION IS MORE THAN ONE THEN ITS CALLED tTEST
# IF POPULATION IS MORE THAN TWO -ITSS CALLED ANNOVA- ANALYSIS OF VARIANCE


In [37]:
import pandas as pd
from scipy.stats import ttest_ind, ttest_ind_from_stats
import numpy as np
np.random.seed(1234567)


In [9]:
#data
df1 = pd.read_csv("https://raw.githubusercontent.com/mahat/TtestExample/master/dataset/MPG_DataSet.csv", sep = ';')

In [10]:
df1.head()

USA  Japan
0   18     24
1   15     27
2   18     27
3   16     25
4   17     31

In [11]:
df1.isna().sum()

USA      0
Japan    0
dtype: int64

In [13]:
df1.shape

(249, 2)

In [14]:
df1

USA  Japan
0     18     24
1     15     27
2     18     27
3     16     25
4     17     31
..   ...    ...
244   27   -999
245   27   -999
246   32   -999
247   28   -999
248   31   -999

[249 rows x 2 columns]

In [17]:
USAMpg = df1['USA'].values
print(USAMpg)

[18 15 18 16 17 15 14 14 14 15 15 14 15 14 22 18 21 21 10 10 11  9 28 25
 19 16 17 19 18 14 14 14 14 12 13 13 18 22 19 18 23 26 25 20 21 13 14 15
 14 17 11 13 12 13 15 13 13 14 22 28 13 14 13 14 15 12 13 13 14 13 12 13
 18 16 18 18 23 11 12 13 12 18 21 19 21 15 16 15 11 20 21 19 15 26 25 16
 16 18 16 13 14 14 14 28 19 18 15 15 16 15 16 14 17 16 15 18 21 20 13 23
 20 23 18 19 25 26 18 16 16 15 22 22 24 23 29 25 20 18 19 18 27 13 17 13
 13 13 30 26 18 17 16 15 18 21 19 19 16 16 16 16 25 26 31 34 36 20 19 20
 19 21 20 25 21 19 21 21 19 18 19 18 18 18 30 31 23 24 22 20 22 20 21 17
 18 17 18 17 16 19 19 36 27 23 24 34 35 28 29 27 34 32 28 26 24 19 28 24
 27 27 26 24 30 39 35 34 30 22 27 20 18 28 27 34 31 29 27 24 23 38 36 25
 38 26 22 36 27 27 32 28 31]


In [19]:
JapanMpg = df1['Japan']
JapanMpg

0       24
1       27
2       27
3       25
4       31
      ... 
244   -999
245   -999
246   -999
247   -999
248   -999
Name: Japan, Length: 249, dtype: int64

In [22]:
JapanMpg = df1['Japan']
JapanMpg_new = JapanMpg[JapanMpg!= -999].values   #to remove vlaues -999 from JapanMPG i.e from Japan column
JapanMpg_new

array([24, 27, 27, 25, 31, 35, 24, 19, 28, 23, 27, 20, 22, 18, 20, 31, 32,
       31, 32, 24, 26, 29, 24, 24, 33, 33, 32, 28, 19, 32, 34, 26, 30, 22,
       22, 33, 39, 36, 28, 27, 21, 24, 30, 34, 32, 38, 37, 30, 31, 37, 32,
       47, 41, 45, 34, 33, 24, 32, 39, 35, 32, 37, 38, 34, 34, 32, 33, 32,
       25, 24, 37, 31, 36, 36, 34, 38, 32, 38, 32], dtype=int64)

In [23]:
print('USA data length %d' % len(USAMpg))
print('Japan data length %d' % len(JapanMpg))
print('Japan new data length %d' % len(JapanMpg_new))

USA data length 249
Japan data length 249
Japan new data length 79


In [21]:
JapanMpg.values

array([  24,   27,   27,   25,   31,   35,   24,   19,   28,   23,   27,
         20,   22,   18,   20,   31,   32,   31,   32,   24,   26,   29,
         24,   24,   33,   33,   32,   28,   19,   32,   34,   26,   30,
         22,   22,   33,   39,   36,   28,   27,   21,   24,   30,   34,
         32,   38,   37,   30,   31,   37,   32,   47,   41,   45,   34,
         33,   24,   32,   39,   35,   32,   37,   38,   34,   34,   32,
         33,   32,   25,   24,   37,   31,   36,   36,   34,   38,   32,
         38,   32, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
       -999, -999, -999, -999, -999, -999, -999, -9

In [26]:
print('USA data mean %f' %  USAMpg.mean())
print('Japan data mean %f' % JapanMpg.mean())
print('Japan new data mean %f' % JapanMpg_new.mean())

USA data mean 20.144578
Japan data mean -672.377510
Japan new data mean 30.481013


In [27]:
np.var(USAMpg)

40.98311317559395

In [28]:
np.var(JapanMpg_new)

36.83191796186508

In [29]:
np.std(USAMpg)

6.401805462179708

In [30]:
np.std(JapanMpg_new)

6.068930545150857

In [39]:
# H1_0 Null Hypothesis = two mean are equal
#significance level = 0.05

significance = 0.05
t, p = ttest_ind(USAMpg, JapanMpg_new, equal_var=False)
print("null hypothesis : MPG means of USA n Japan are equal")
print("t_value =%g P- value = %g significance = %g" % (t, p, significance))

#H1 = Two means are not 

if p<significance:
    print("Reject null hypothesis -> Population mean MPG of Japan & USA are not equal")
else:
    print("Fails to reject Null hypothesis")

null hypothesis : MPG means of USA n Japan are equal
t_value =-12.9463 P- value = 1.57085e-25 significance = 0.05
Reject null hypothesis -> Population mean MPG of Japan & USA are not equal


In [33]:
JapanMpg_new

array([24, 27, 27, 25, 31, 35, 24, 19, 28, 23, 27, 20, 22, 18, 20, 31, 32,
       31, 32, 24, 26, 29, 24, 24, 33, 33, 32, 28, 19, 32, 34, 26, 30, 22,
       22, 33, 39, 36, 28, 27, 21, 24, 30, 34, 32, 38, 37, 30, 31, 37, 32,
       47, 41, 45, 34, 33, 24, 32, 39, 35, 32, 37, 38, 34, 34, 32, 33, 32,
       25, 24, 37, 31, 36, 36, 34, 38, 32, 38, 32], dtype=int64)

In [34]:
len(JapanMpg_new)

79